name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.PROJECT_ID }}/flask:latest .

      - name: Push
        run: |
          docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/flask:latest

      - name: Deploy
        run: |
          gcloud run deploy flask \
          --region europe-north1-a \
          --image eu.gcr.io/${{ secrets.PROJECT_ID }}/flask \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.PROJECT_ID }}
