name: Trade Website

# Controls when the workflow will run

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]




jobs:
  cd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # macOS was chosen because of how the runner interprets the file paths. File paths are having problems when used in other runners.

    steps:
#       - name: Initialises the Google Cloud CLI
#         uses: google-github-actions/setup-gcloud@main
#         with:
#           service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
#           project_id: ${{ secrets.PROJECT_ID }}
#           export_default_credentials: true
#       - name: Downloading the Repository
#         uses: actions/checkout@v2     
#       - name: Image
#         run: |-
#             docker build . -t eu.gcr.io/${{ secrets.PROJECT_ID }}/flask
#       - name: Webserver
#         run: |-
#             docker build frontend/frontend/. -t eu.gcr.io/${{ secrets.PROJECT_ID }}/webserver      
#       - run:  gcloud auth configure-docker -q

#       # Push image to Google Container Registry
#       - name: Build
#         run: |-
#           docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/flask 
          
          
#       - name: Build
#         run: |-
#           docker push eu.gcr.io/${{ secrets.PROJECT_ID }}/webserver    
              
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.GCP_PORT }}
          script: whoami
